# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('js_locations', '0005_auto_20190523_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='featured_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='featured image'),
        ),
    ]
