# Generated by Django 2.2.10 on 2020-10-26 16:23

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_locations', '0007_auto_20190709_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificLocationsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('layout', models.CharField(blank=True, max_length=30, null=True, verbose_name='layout')),
                ('more_button_is_shown', models.BooleanField(blank=True, default=False, verbose_name='Show “See More Button”')),
                ('more_button_text', models.CharField(blank=True, max_length=255, verbose_name='See More Button Text')),
                ('more_button_link', models.CharField(blank=True, max_length=255, verbose_name='See More Button Link')),
                ('locations', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_locations.Location', verbose_name='locations')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
