# Generated by Django 2.2.18 on 2021-02-16 13:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_locations', '0009_auto_20201116_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
