# Generated by Django 2.2.19 on 2021-03-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_locations', '0010_location_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='namespace',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Instance namespace'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(default='js_locations.Location', max_length=100, verbose_name='Type'),
        ),
    ]
