# Generated by Django 2.2.24 on 2021-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_locations', '0012_auto_20211125_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address_locality',
            field=models.TextField(blank=True, verbose_name='address locality'),
        ),
        migrations.AddField(
            model_name='location',
            name='currencies_accepted',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='currencies accepted'),
        ),
        migrations.AddField(
            model_name='locationtranslation',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
